apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: carlosviniciusoliv/auth
    context: auth
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - Infra/k8s/auth-depl.yaml
